# Generated by Django 5.1.3 on 2024-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfriCreate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures/'),
        ),
    ]
