# Generated by Django 5.1.3 on 2024-11-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfriCreate', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile-icon.png', upload_to='profile_pictures/'),
        ),
    ]
