# Generated by Django 5.1.3 on 2024-11-24 13:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AfriCreate', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqky44kl4/image/upload/v1732417617/x0xnry4m57a0mpoasps9.webp', max_length=255, verbose_name='image'),
        ),
    ]
